version: "3.8"
services:
   graph:
      image: unifarm/unifarm-testnet-graph:2.0.2
      env_file: "./.env.prod"
      volumes:
         - graph:/graph/storage
      ports:
         - "8080:8080"   
      networks:
         - unifarm
      command: ["run","graph:start"]   
      deploy:
         mode: "replicated"
         replicas: 3
         placement:
            max_replicas_per_node: 2
         restart_policy:
            condition: on-failure
   eth-events-sync:
      image: unifarm/unifarm-testnet-events:4.4.4
      env_file: "./.env.prod"
      environment:
         - CHAIN_ID=4
      volumes:
         - eth_events:/events/storage
      networks:
         - unifarm
      command: ["run","listener-server:start"]     
      deploy:
         mode: "replicated"
         restart_policy:
            condition: on-failure     
   bsc-events-sync:
      image: unifarm/unifarm-testnet-events:4.4.4
      env_file: "./.env.prod"
      environment:
         - CHAIN_ID=97
      volumes:
         - bsc_events:/events/storage
      networks:
         - unifarm
      command: ["run","listener-server:start"]
      deploy:
         mode: "replicated"
         restart_policy:
            condition: on-failure

   polygon-events-sync:
      image: unifarm/unifarm-testnet-events:4.4.4
      env_file: "./.env.prod"
      environment:
         - CHAIN_ID=80001
      volumes:
         - polygon_events:/events/storage
      networks:
         - unifarm
      command: ["run","listener-server:start"]     
      deploy:
         mode: "replicated"
         restart_policy:
            condition: on-failure
   redis:
      image: redis:latest
      volumes:
         - redis-data:/data
      ports:
         - "6379:6379"
      networks:
         - unifarm
      command: redis-server --appendonly yes  --requirepass TdePagKTvyhAcnYR   
      deploy:
         mode: "replicated"
         replicas: 1
         placement:
            constraints:
               - "node.role==manager"
         restart_policy:
            condition: on-failure                 
networks:
   unifarm:
volumes:
   graph:
   eth_events:
   bsc_events:
   polygon_events:
   redis-data:      
