version: "3.8"
services:
   graph:
      image: unifarm/unifarm-mainnet-graph:latest
      env_file: "./.env.prod"
      volumes:
         - graph:/graph
      ports:
         - "8080:8080"   
      networks:
         - unifarm
      command: ["run","graph:start"]   
      deploy:
         mode: "replicated"
         replicas: 3
         placement:
            max_replicas_per_node: 1
         restart_policy:
            condition: on-failure
   eth-events-sync:
      image: unifarm/unifarm-mainnet-events:2.0.1
      env_file: "./.env.prod"
      volumes:
         - eth-events-logs:/events/storage
      environment:
         - CHAIN_ID=1
      networks:
         - unifarm
      command: ["run","listener-server:start"]
      depends_on: 
         - redis     
      deploy:
         mode: "replicated"
         restart_policy:
            condition: on-failure     
   bsc-events-sync:
      image: unifarm/unifarm-mainnet-events:2.0.1
      env_file: "./.env.prod"
      volumes:
         - bsc-events-logs:/events/storage
      environment:
         - CHAIN_ID=56
      networks:
         - unifarm
      command: ["run","listener-server:start"]
      depends_on: 
         - redis
      deploy:
         mode: "replicated"
         restart_policy:
            condition: on-failure

   polygon-events-sync:
      image: unifarm/unifarm-mainnet-events:2.0.1
      env_file: "./.env.prod"
      volumes:
         - polygon-events-logs:/events/storage
      environment:
         - CHAIN_ID=137
      networks:
         - unifarm
      command: ["run","listener-server:start"]
      depends_on: 
         - redis     
      deploy:
         mode: "replicated"
         restart_policy:
            condition: on-failure
   redis:
      image: redis:latest
      volumes:
         - redis-data:/data
      ports:
         - "6379:6379"
      networks:
         - unifarm
      command: redis-server --appendonly yes  --requirepass STTjrAbH2tKu6c3c   
      deploy:
         mode: "replicated"
         replicas: 1
         placement:
            constraints:
               - "node.role==manager"
         restart_policy:
            condition: on-failure                 
networks:
   unifarm:
volumes:
   graph:
   eth-events-logs:   
   bsc-events-logs:   
   polygon-events-logs:   
   redis-data:      
